name: Ejercicio 1

on:
  push:
    branches:
      - main        
      - principal   

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Decir mi nombre
        run: echo "Hola, mi nombre es David Joel Rivas Ortega"

      - name: Mostrar fecha y hora
        run: date

      - name: Mostrar sistema operativo
        run: |
          echo "Sistema operativo: $RUNNER_OS"
